services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: knihovnik
      POSTGRES_USER: ${SERVICE_USER_POSTGRES}
      POSTGRES_PASSWORD: ${SERVICE_PASSWORD_POSTGRES}
    volumes:
      - db-data:/var/lib/postgresql/data
